name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Build Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o mktouch-linux-amd64
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: mktouch-linux-amd64
          path: ./mktouch-linux-amd64
      
      - name: Get Release ID
        id: get_release
        run: echo "::set-output name=release_id::$(echo ${{ steps.create_release.outputs.release_id }})"
      
      - name: Attach Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mktouch-linux-amd64
          asset_name: mktouch-linux-amd64
          asset_content_type: application/octet-stream
